markdown: redcarpet
highlighter: pygments
logo: false                                                                                                                                           c-14
paginate: 15
baseurl: ""
domain_name: 'https://ludeliang.github.io'
baseurl: "/solu" # the subpath of your site, e.g. /blog/
# Details for the RSS feed generator
url: "https://ludeliang.github.io/solu" # the base hostname & protocol for your site
author:         'ludeliang'
name:          'JS算法集锦'
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'config.ru', 'unicorn.rb', 'Procfile']